border:
  - name: 8
    px: 42,30,36,51
  - name: 9
    px: 0,28,0,35
  - name: 10
    px: 5,25,15,50
  - name: 11
    px: 0,28,0,18
  - name: 12
    px: 15,25,15,20
  - name: 13
    px: 8,8,6,10
  - name: 14
    px: 20,30,15,25
activate: 9
source_dir: E:\temp\source1
target_dir: E:\temp\target1
auto_start: true